Refactoring of old actions to be reusable

diff --git a/.github/actions/setup-apax-runner/action.yml b/.github/actions/setup-apax-runner/action.yml
--- a/.github/actions/setup-apax-runner/action.yml
+++ b/.github/actions/setup-apax-runner/action.yml
@@ -19,7 +19,49 @@ runs:
       shell: bash
       env:
         APAX_TOKEN: ${{ inputs.apax-access-token }}
-        SCRIPT_PATH: actions
+        SCRIPT_PATH: ax_ci_workflows
       run: |
-        sudo chmod +x ./$SCRIPT_PATH/scripts/setup-apax-env_ubuntu.sh
+        chmod +x ./$SCRIPT_PATH/scripts/setup-apax-env_ubuntu.sh
         ./$SCRIPT_PATH/scripts/setup-apax-env_ubuntu.sh $APAX_TOKEN
+        if command -v apax &>/dev/null; then
+          echo "Apax already installed, skip installation"
+          apax login -p $1
+          exit 0
+        fi
+
+        if ! command -v apt-get &>/dev/null; then
+          echo "Error: apt has not been found, make sure that apt is installed"
+          exit 1
+        fi
+        apt-get install --assume-yes --no-install-recommends \
+        libtinfo5 \
+        git nodejs
+        mkdir apax-dep
+        npm config set prefix "~/.local/"
+        mkdir -p ~/.local/bin
+        echo 'export PATH=~/.local/bin/:$PATH' >>~/.bashrc
+        npm init -y
+        curl -H "Authorization: bearer $1" "https://api.prod.ax.siemens.cloud/apax/login?format=npmrc"  >.npmrc
+        npm add @ax/apax-signed
+        npm install
+        cd node_modules/@ax/apax-signed
+        echo "-----BEGIN PUBLIC KEY-----" \
+        >public.pem
+        echo "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4m2LqXil8zyn+Z9v0J93" \
+        >>public.pem
+        echo "03hNjjrw6JMKvj0skNJvSaNPq1cYwq1Q/cu86Ny/Wl+lJT+Nzl32oKcgPuU+eY1Z" \
+        >>public.pem
+        echo "VTm9ZYPmIuoO+WPEsW5v1q8u7LURJt5jMxyfVQLXakUzkrjdQY+8/fO77R/s7ndi" \
+        >>public.pem
+        echo "qOXvoDw4SC8RAcbFVoske7R9L8nr8+lAjyOAs7fcWEOAkXaFF3BNIddxAGtAjXr5" \
+        >>public.pem
+        echo "5y+ecHh0wom+diN3RdSDk5TqKl9F8lThAqd8LjFxRcjaeaKftruTB9yd+ppN/4wl" \
+        >>public.pem
+        echo "avwaTQ/7eYHbvNV5aYeELUzxFykhsqKlIeo93y/ncnU0xS7W6ccCvNJ74kRfRtJY" \
+        >>public.pem
+        echo "WwIDAQAB" \
+        >>public.pem
+        echo "-----END PUBLIC KEY-----" \
+        >>public.pem
+        openssl dgst -sha256 -verify public.pem -signature ax-apax.sig ax-apax-*.tgz
+        npm install -g ax-apax-*.tgz
